#define MAX_POKEMON_PARTY 6
#define MAX_ITEMS 128
#define NUM_BADGES 8
#define MAX_MOVES 4
#define NUM_POKEMON 151

#define MAX_DIALOGUE_STRINGS 30
#define MAX_SPRITES 4096

#define MAX_AREA_ROWS 500
#define MAX_AREA_COLS 500
#define MAX_AREAS 128
#define TILE_X_SIZE 50
#define TILE_Y_SIZE 50